logging:
  path: ./logs

eureka:
  client:
    serviceUrl:
      defaultZone: https://jalgoarena-eureka-koscinsa.herokuapp.com/eureka/

server:
  port: ${PORT:5003}

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${APP_NAME:jalgoarena-submissions-koscins}.herokuapp.com
    nonSecurePort: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
